// 05-integracao-vue/src/components/Contador.vue
<template>
  <div>
    <h1>Contador</h1>
    <h2>{{ valor }}</h2>
    <button @click="setValor(-1)">Dec</button>
    <button @click="setValor(1)">Inc</button>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
export default Vue.extend({
  props: {
    valorInicial: {
      type: Number,
    },
  },
  data() {
    return {
      valor: this.valorInicial || 0,
    };
  },
  methods: {
    setValor(delta: number) {
      this.valor += delta;
    },
  },
});
</script>

<style></style>

// 04-integracao-react/src/components/Contador.tsx
import React, { Component } from "react";
import ContadorValor from "./ContadorValor";
import "./Contador.css";
import logRender from '../decorators/logRender';

interface ContadorProps {
  valorInicial?: number;
}

interface ContadorState {
  valor: number;
}

@logRender
export default class Contador extends Component<ContadorProps, ContadorState> {
  public state = { valor: this.props.valorInicial || 0 };

  private setvalor = (delta: number) => {
    this.setState({
      valor: this.state.valor + delta,
    });
  };

  render(): React.ReactNode {
    return (
      <div>
        <ContadorValor contador={this.state.valor} />
        <button onClick={() => this.setvalor(10)}>+</button>
        <button onClick={() => this.setvalor(-10)}>-</button>
      </div>
    );
  }
}
